Release/2.1.1
snowplow/snowplow-s3-loader pull request #244
Opened 2021-12-14 23:44 UTC by istreeter

2021-12-14 23:44 UTC, snowplowcla commented
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/ to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

2021-12-15 07:45 UTC, benjben requested changes
Looks great ! Just one thing to fix : the issue number for `Exlude transitive dependencies of hadoop (#234)` is not 234 but 243. Do you want me to fix this ?

2021-12-15 08:39 UTC, benjben commented
I did it

2021-12-15 08:39 UTC, benjben approved these changes

2021-12-15 09:05 UTC, merged